language: java
jdk:
  - oraclejdk8
  - openjdk8

sudo: required

services:
  - docker

install:
  - make clean

script:
  - make build

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - make deploy
  